### ISSUE TITLE
how to start my friend

### ISSUE THREAD

**Issue by kiing98** [dilushanka/Telegram-group-members-adder#1]
how to start

**Comment by dilushanka** [comment]
1. install python on your pc.
2. download and extract these codes
3. replace these credentials in add.py code " # Replace 'API_ID' and 'API_HASH' with your actual API ID and API Hash
api_id = 'Your-API-ID'
api_hash = 'You-API-hash'
phone = 'Phone-Number'  # Include country code, e.g., +123456789 "
4. run this command in your CMD " pip install -r requirements.txt "
5. run this add.py in cmd " python /path/to/your/add.py "
